---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-control
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: control
  template:
    metadata:
      labels:
        app: myapp
        type: control
    spec:
      containers:
        - name: myapp
          image: saireddysatishkumar/myapp:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
